In [3]:
a = [1,2,3,4]
b = "a" + "10"
print(b)

a10


In [4]:
a = [1,2,3,4]
b = [1,2,3,5]
c = a+b
print(c)


[1, 2, 3, 4, 1, 2, 3, 5]


In [6]:
import numpy as np
a = np.array(a)
a+10

array([11, 12, 13, 14])

In [8]:
import numpy as np
a = np.array(a)
a+10


array([11, 12, 13, 14])

In [13]:
a5 = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
a6 = [14,15,16]
range(6)
range(0,6)

range(0, 6)

In [11]:
for i in range(6):
    print(i)

0
1
2
3
4
5


In [15]:
np.arange(0,8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [41]:
print(data.head())
print(data.info())


   age  education-num  race  sex  capital-gain  capital-loss  hours-per-week  \
0   39             13     4    1          2174             0              40   
1   50             13     4    1             0             0              13   
2   38              9     4    1             0             0              40   
3   53              7     2    1             0             0              40   
4   28             13     2    0             0             0              40   

   income  
0       0  
1       0  
2       0  
3       0  
4       0  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             1000 non-null   int64
 1   education-num   1000 non-null   int64
 2   race            1000 non-null   int64
 3   sex             1000 non-null   int64
 4   capital-gain    1000 non-null   int64
 5   capital-loss    1000 non-null   int6

In [42]:
import os
print(os.getcwd())

C:\Users\sumit\MicrosoftCertificate


In [43]:
data = pd.read_csv("C:/Users/sumit/MicrosoftCertificate/data.csv")

In [47]:
import pandas as pd

data = pd.read_csv("data.csv", encoding='latin1')
arr = data.to_numpy()

print(arr[:5])

[[  39   13    4    1 2174    0   40    0]
 [  50   13    4    1    0    0   13    0]
 [  38    9    4    1    0    0   40    0]
 [  53    7    2    1    0    0   40    0]
 [  28   13    2    0    0    0   40    0]]


In [49]:
# ARRAY OPERATIONS
print(arr.shape)    # (rows, columns)
print(arr.ndim)     # dimensions
print(arr.size)     # total elements
print(arr.dtype)    # data type

(1000, 8)
2
8000
int64


In [50]:
# INDEXING AND SLICING
arr[0]        # first row
arr[:, 0]     # first column
arr[0:5]      # first 5 rows
arr[1:3, 0:2] # sub-matrix

array([[50, 13],
       [38,  9]])

In [51]:
# MATHIMATICAL OPERATIONS
arr + 10
arr - 5
arr * 2
arr / 2
arr ** 2

array([[1521,  169,   16, ...,    0, 1600,    0],
       [2500,  169,   16, ...,    0,  169,    0],
       [1444,   81,   16, ...,    0, 1600,    0],
       ...,
       [2304,  169,   16, ...,    0, 3364,    1],
       [1600,  100,   16, ...,    0, 1600,    0],
       [1521,  169,   16, ...,    0, 2500,    1]], shape=(1000, 8))

In [52]:
# Statistical Operations
np.mean(arr)
np.median(arr)
np.std(arr)
np.var(arr)
np.sum(arr)
np.min(arr)
np.max(arr)

np.int64(34095)

In [53]:
np.mean(arr)

np.float64(96.756625)

In [54]:
np.mean(arr, axis=0)

array([3.80510e+01, 1.00840e+01, 3.65300e+00, 6.71000e-01, 5.88526e+02,
       9.29600e+01, 3.98760e+01, 2.32000e-01])

In [55]:
# Boolean Operations (Filtering)
arr > 50
arr[arr > 50]

array([ 2174,    53,    52, 14084,  5178,    80,    60,    54,  2042,
          59,    56,    54,    60,    80,    52,  1408,    53,    57,
          53,  1902,    60,    55,    60,  5013,  2407,    58,    53,
          70,    79,    67,    52,    59, 14344,    53,    57,  1573,
        1902,    60,    76, 15024,    60,  7688, 34095,    56,  1887,
        4064,    53,    56,    55,    56,    60,  1719,    60,  1762,
        4386,    60,    61,  1564,    70,    64,  2179,    52,    71,
        1816,    60,    68,    66,  1980,    51,  1977,    65,    53,
          58, 14084,    55,  7298,  1876,    51,  1340,  7298,    60,
          58, 15024,    60,    54,    60,    55,    64,    90,  2206,
          54,    53,    60,    66,  1409,    75,    65,  3674,    55,
          59,    70,  1741,    56,    58,  1977,    60,    59,    58,
          60,    59,  4064,    75,    64,    61,  1055,  2407,    98,
        7298,  7298,  5178,    60,    57, 15024,    60,    56,    65,
          60,  3464,

In [56]:
# Conditional Selection
np.where(arr > 50, 1, 0)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1000, 8))

In [57]:
# Sorting
np.sort(arr, axis=0)   # column-wise
np.sort(arr, axis=1)   # row-wise

array([[    0,     0,     1, ...,    39,    40,  2174],
       [    0,     0,     0, ...,    13,    13,    50],
       [    0,     0,     0, ...,     9,    38,    40],
       ...,
       [    0,     0,     1, ...,    13,    48,    58],
       [    0,     0,     1, ...,    40,    40,  2580],
       [    0,     1,     1, ...,    39,    50, 15024]], shape=(1000, 8))

In [58]:
# Aggregation
np.sum(arr, axis=0)
np.max(arr, axis=1)

array([ 2174,    50,    40,    53,    40,    40,    49,    52, 14084,
        5178,    80,    40,    30,    50,    40,    45,    35,    40,
          50,    45,    60,    54,    40,  2042,    59,    56,    40,
          60,    80,    49,    52,    44,  1408,    40,    22,    48,
          40,    25,    38,    48,    43,    53,    50,    49,    35,
          57,    53,    44,    41,    43,    40,    30,  1902,    55,
          60,    43,    46,    40,    48,  5013,  2407,    40,    48,
          45,    58,    40,    40,    53,    50,    40,    32,    40,
          70,    40,    79,    40,    40,    67,    22,    40,    30,
          52,    46,    59, 14344,    53,    49,    50,    40,    50,
          57,    40,    28,  1573,    40,    50,  1902,    48,    48,
          40,    76, 15024,    50,    40,    40,  7688, 34095,    40,
          40,    42,    40,    40,  1887,  4064,    40,    53,    56,
          49,    56,    41,    40,    60,    40,    50,    35,    47,
        1719,    40,

In [59]:
# Reshaping
arr.reshape(2, -1)
arr.flatten()

array([39, 13,  4, ...,  0, 50,  1], shape=(8000,))

In [61]:
np.delete(arr, 0, axis=0)   # delete row
np.delete(arr, 0, axis=1)   # delete column

array([[13,  4,  1, ...,  0, 40,  0],
       [13,  4,  1, ...,  0, 13,  0],
       [ 9,  4,  1, ...,  0, 40,  0],
       ...,
       [13,  4,  1, ...,  0, 58,  1],
       [10,  4,  1, ...,  0, 40,  0],
       [13,  4,  1, ...,  0, 50,  1]], shape=(1000, 7))

In [62]:
# Unique & Count
np.unique(arr)

array([    0,     1,     2,     3,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63,    64,    65,    66,    67,    68,    69,    70,    71,
          72,    73,    74,    75,    76,    77,    78,    79,    80,
          81,    90,    98,    99,   594,   653,  1055,  1111,  1340,
        1380,  1408,  1409,  1485,  1504,  1564,  1573,  1669,  1672,
        1719,  1721,  1741,  1762,  1816,  1876,  1887,  1902,  1977,
        1980,  2042,  2050,  2051,  2174,  2176,  2179,  2206,  2339,
        2352,  2377,  2392,  2407,  2415,  2463,  2580,  2597,  2964,
        3103,  3325,

In [63]:
# Matrix Operations
arr.T                # transpose
np.dot(arr, arr.T)   # matrix multiplication

array([[  4729583,      2656,      3216, ...,      4378,   5612227,
         32665883],
       [     2656,      2855,      2554, ...,      3340,      2667,
             2786],
       [     3216,      2554,      3142, ...,      4278,      3227,
             3616],
       ...,
       [     4378,      3340,      4278, ...,      5855,      4387,
             4959],
       [  5612227,      2667,      3227, ...,      4387,   6659717,
         38765627],
       [ 32665883,      2786,      3616, ...,      4959,  38765627,
        225724784]], shape=(1000, 1000))

In [64]:
# Handling Missing Values
np.isnan(arr)
np.nan_to_num(arr)

array([[39, 13,  4, ...,  0, 40,  0],
       [50, 13,  4, ...,  0, 13,  0],
       [38,  9,  4, ...,  0, 40,  0],
       ...,
       [48, 13,  4, ...,  0, 58,  1],
       [40, 10,  4, ...,  0, 40,  0],
       [39, 13,  4, ...,  0, 50,  1]], shape=(1000, 8))

In [65]:
# Logical Operations
np.logical_and(arr > 10, arr < 50)

array([[ True,  True, False, ..., False,  True, False],
       [False,  True, False, ..., False,  True, False],
       [ True, False, False, ..., False,  True, False],
       ...,
       [ True,  True, False, ..., False, False, False],
       [ True, False, False, ..., False,  True, False],
       [ True,  True, False, ..., False, False, False]], shape=(1000, 8))

In [66]:
# Stacking
np.vstack((arr, arr))
np.hstack((arr, arr))

array([[39, 13,  4, ...,  0, 40,  0],
       [50, 13,  4, ...,  0, 13,  0],
       [38,  9,  4, ...,  0, 40,  0],
       ...,
       [48, 13,  4, ...,  0, 58,  1],
       [40, 10,  4, ...,  0, 40,  0],
       [39, 13,  4, ...,  0, 50,  1]], shape=(1000, 16))

In [67]:
# Splitting
np.split(arr, 2)

[array([[39, 13,  4, ...,  0, 40,  0],
        [50, 13,  4, ...,  0, 13,  0],
        [38,  9,  4, ...,  0, 40,  0],
        ...,
        [23,  3,  4, ...,  0, 40,  0],
        [26, 10,  4, ...,  0, 35,  0],
        [72,  9,  4, ...,  0, 20,  0]], shape=(500, 8)),
 array([[23,  9,  4, ...,  0, 40,  0],
        [62,  9,  4, ...,  0, 40,  0],
        [52, 10,  4, ...,  0, 40,  0],
        ...,
        [48, 13,  4, ...,  0, 58,  1],
        [40, 10,  4, ...,  0, 40,  0],
        [39, 13,  4, ...,  0, 50,  1]], shape=(500, 8))]

In [68]:
# Save Back to CSV
np.savetxt("output.csv", arr, delimiter=",")